import { varMode } from "./constants.js";

export const init_variables = {
  C: 100,
  I: 300,
  G: 100,
  T: 50,
  Xn: 50,
  mpc: 0.8,
  phi: 10,
  bi: 30,
  bY: 0,
  etaY: 0.14,
  etaYstar: 0,
  etaQ: 5,
  Ms: 400,
  Q: 2,
  P: 2,
  Lbar: 0,
  lambdaY: 0.5,
  lambdai: 50,
  tY: 0.2,
  theta: 0,
  istar: 3,
  c: 10,
  Ystar: 0,
};

export const econVars = [
  {
    key: "C",
    label: "$\\bar{C}$",
    value: init_variables["C"],
    editable: varMode.EDITABLE,
    min: 0,
    max: 500,
    step: 1,
  },
  {
    key: "I",
    label: "$\\bar{I}$",
    value: init_variables["I"],
    editable: varMode.NOT_EDITABLE,
  },
  {
    key: "G",
    label: "$\\bar{G}$",
    value: init_variables["G"],
    editable: varMode.NOT_EDITABLE,
  },
  {
    key: "T",
    label: "$\\bar{T}$",
    value: init_variables["T"],
    editable: varMode.EDITABLE,
    min: 0,
    max: 500,
    step: 1,
  },
  {
    key: "Xn",
    label: "$\\bar{X}_n$",
    value: init_variables["Xn"],
    editable: varMode.EDITABLE,
    min: 0,
    max: 500,
    step: 1,
  },
  {
    key: "mpc",
    label: "$mpc$",
    value: init_variables["mpc"],
    editable: varMode.EDITABLE,
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    key: "phi",
    label: "$\\phi$",
    value: init_variables["phi"],
    editable: varMode.NOT_EDITABLE,
  },
  {
    key: "bi",
    label: "$b_i$",
    value: init_variables["bi"],
    editable: varMode.NOT_EDITABLE,
  },
  {
    key: "bY",
    label: "$b_Y$",
    value: init_variables["bY"],
    editable: varMode.NOT_EDITABLE,
  },
  {
    key: "etaY",
    label: "$\\eta_Y$",
    value: init_variables["etaY"],
    editable: varMode.NOT_EDITABLE,
  },
  {
    key: "etaYstar",
    label: "$\\eta_{Y^*}$",
    value: init_variables["etaYstar"],
    editable: varMode.NOT_EDITABLE,
  },
  {
    key: "etaQ",
    label: "$\\eta_Q$",
    value: init_variables["etaQ"],
    editable: varMode.NOT_EDITABLE,
  },
  {
    key: "Ms",
    label: "$M_s$",
    value: init_variables["Ms"],
    editable: varMode.EDITABLE,
    min: 0,
    max: 1000,
    step: 1,
  },
  {
    key: "Q",
    label: "$Q$",
    value: init_variables["Q"],
    editable: varMode.EDITABLE,
    min: 0,
    max: 100,
    step: 1,
  },
  {
    key: "P",
    label: "$P$",
    value: init_variables["P"],
    editable: varMode.NOT_EDITABLE,
  },
  {
    key: "Lbar",
    label: "$\\bar{L}$",
    value: init_variables["Lbar"],
    editable: varMode.NOT_EDITABLE,
  },
  {
    key: "lambdaY",
    label: "$\\lambda_Y$",
    value: init_variables["lambdaY"],
    editable: varMode.NOT_EDITABLE,
  },
  {
    key: "lambdai",
    label: "$\\lambda_i$",
    value: init_variables["lambdai"],
    editable: varMode.NOT_EDITABLE,
  },
  {
    key: "tY",
    label: "$t_Y$",
    value: init_variables["tY"],
    editable: varMode.EDITABLE,
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    key: "theta",
    label: "$\\theta$",
    value: init_variables["theta"],
    editable: varMode.NOT_EDITABLE,
  },
  {
    key: "istar",
    label: "$i^*$",
    value: init_variables["istar"],
    editable: varMode.NOT_EDITABLE,
    min: 0,
    max: 10,
    step: 0.01,
  },
  {
    key: "c",
    label: "$c$",
    value: init_variables["c"],
    editable: varMode.NOT_EDITABLE,
  },
  {
    key: "Ystar",
    label: "$Y^*$",
    value: init_variables["Ystar"],
    editable: varMode.NOT_EDITABLE,
  },
];
